trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  configuration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: '.NET build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(configuration)'
- task: DotNetCoreCLI@2
  displayName: '.NET test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(configuration) --logger "xunit;LogFileName=TestResults.xml" --collect "Code coverage"'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TestResults.xml'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'mi/mi.csproj'
    arguments: '--configuration $(configuration) --output $(Build.ArtifactStagingDirectory)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'