trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  displayName: '.NET build'
  inputs:
    script: 'dotnet build --configuration $(buildConfiguration)'
- task: CmdLine@2
  displayName: '.NET test'
  enabled: false
  inputs:
    script: 'dotnet test "./Minsk.Tests/Minsk.Tests.csproj" --logger "xunit;LogFileName=TestResults.xml"'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  enabled: false
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/TestResults.xml'