name: CI
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:
env:
  CONFIGURATION: 'Release'
jobs:
  build-and-test:
    name: build-and-test--${{ matrix.os-version }}
    runs-on: ${{ matrix.os-version }}
    strategy:
      matrix:
        os-version: [windows-latest] #, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: .NET setup
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: .NET info
        run: dotnet --info
      - name: .NET restore
        run: dotnet restore Minsk.Compiler.slnf
      - name: .NET build
        run: dotnet build Minsk.Compiler.slnf --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: .NET test
        run: dotnet test Minsk.Compiler.slnf --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal
      - name: .NET pack
        run: dotnet pack Minsk.Compiler.slnf --configuration ${{ env.CONFIGURATION }} --no-build --no-restore --verbosity normal