name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#    paths:
#    - '**.cs'
#    - '**.csproj'
  workflow_dispatch:
env:
    CONFIGURATION: 'Release'
jobs:
  build-and-test:
    name: build-and-test--${{ matrix.os-version }}
    runs-on: ${{ matrix.os-version }}
    strategy:
      matrix:
        os-version: [windows-latest] #, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: dotnet setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: dotnet info
        run: dotnet --info
      - name: dotnet restore
        run: dotnet restore ./src
      - name: dotnet build
        run: dotnet build ./src/Minsk.sln --no-restore
      - name: dotnet test
        run: dotnet test ./src/Minsk.Tests/Minsk.Tests.csproj --no-build --verbosity normal